services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: 'php-cli'
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "9001:9001"
#    entrypoint: ["/var/www/html/docker/php/xdebug-entrypoint.sh"]
    command: ["sh", "-c", "composer install && php index.php"]


